import os
import json
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Path to the results directory relative to project root
RESULTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "results")
HISTORY_FILE = os.path.join(RESULTS_DIR, "training_history.json")


def ensure_results_dir_exists():
    """
    Ensures that the results/ directory exists on disk.
    """
    if not os.path.exists(RESULTS_DIR):
        os.makedirs(RESULTS_DIR)


def calculate_metrics(y_true, y_pred):
    """
    Calculates RMSE, MAE, and MAPE between true values and predicted values.

    Parameters:
        y_true (array-like): Ground truth / actual price values.
        y_pred (array-like): Predicted price values generated by the model.

    Returns:
        dict: Dictionary containing calculated metrics:
            {
                "RMSE": float,
                "MAE": float,
                "MAPE": float
            }
    """
    # Convert inputs to 1D numpy arrays and flatten
    y_true = np.array(y_true, dtype=float).flatten()
    y_pred = np.array(y_pred, dtype=float).flatten()

    # Remove non-finite values (NaN / Inf) if any exist
    valid_mask = np.isfinite(y_true) & np.isfinite(y_pred)
    y_true = y_true[valid_mask]
    y_pred = y_pred[valid_mask]

    if len(y_true) == 0 or len(y_pred) == 0:
        return {"RMSE": 0.0, "MAE": 0.0, "MAPE": 0.0}

    # 1. Root Mean Square Error (RMSE)
    mse = mean_squared_error(y_true, y_pred)
    rmse = float(np.sqrt(mse))

    # 2. Mean Absolute Error (MAE)
    mae = float(mean_absolute_error(y_true, y_pred))

    # 3. Mean Absolute Percentage Error (MAPE)
    non_zero_mask = y_true != 0
    if np.any(non_zero_mask):
        mape = float(
            np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100
        )
    else:
        mape = 0.0

    return {
        "RMSE": round(rmse, 4),
        "MAE": round(mae, 4),
        "MAPE": round(mape, 4)
    }


def save_metrics_to_json(model_name, stock_name, metrics):
    """
    Saves computed model metrics to a JSON file in the results/ folder.

    Parameters:
        model_name (str): Name of the model ('Prophet', 'ARIMA', 'LSTM').
        stock_name (str): Name of stock dataset (e.g. 'AAPL.csv').
        metrics (dict): Metrics dictionary computed by calculate_metrics().
    """
    ensure_results_dir_exists()
    
    clean_stock = stock_name.replace(".csv", "")
    filename = f"{clean_stock}_{model_name.lower()}_metrics.json"
    file_path = os.path.join(RESULTS_DIR, filename)

    payload = {
        "stock": clean_stock,
        "model": model_name,
        "metrics": metrics,
        "timestamp": pd.Timestamp.now().isoformat()
    }

    try:
        with open(file_path, "w") as f:
            json.dump(payload, f, indent=4)
    except Exception as e:
        print(f"Failed to save metrics JSON: {e}")


def save_training_run_to_history(stock_name, model_name, forecast_df, metrics, interpretability):
    """
    Persists a complete training run snapshot (including full forecast DataFrame points,
    metrics, and interpretability insights) to results/training_history.json.

    Parameters:
        stock_name (str): Asset name (e.g. 'AAPL.csv').
        model_name (str): Model name ('Prophet', 'ARIMA', 'LSTM').
        forecast_df (pd.DataFrame): Unified forecast DataFrame.
        metrics (dict): RMSE, MAE, MAPE dict.
        interpretability (dict): AI Forecast Interpretability dict.
    """
    ensure_results_dir_exists()
    
    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    clean_stock = stock_name.replace(".csv", "")
    run_id = f"{clean_stock}_{model_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    # Convert DataFrame to JSON serializable list of records
    df_copy = forecast_df.copy()
    if "Date" in df_copy.columns:
        df_copy["Date"] = df_copy["Date"].astype(str)

    run_record = {
        "run_id": run_id,
        "label": f"{clean_stock} — {model_name} ({timestamp_str})",
        "stock": clean_stock,
        "model": model_name,
        "timestamp": timestamp_str,
        "metrics": metrics,
        "interpretability": interpretability,
        "forecast_data": df_copy.to_dict(orient="records")
    }

    # Load existing history or start fresh
    history = []
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE, "r") as f:
                history = json.load(f)
        except Exception:
            history = []

    # Prepend newest run to history
    history.insert(0, run_record)

    # Limit history to latest 50 training runs to prevent excessive file size
    history = history[:50]

    try:
        with open(HISTORY_FILE, "w") as f:
            json.dump(history, f, indent=2)
    except Exception as e:
        print(f"Failed to save training run to history: {e}")


def load_all_training_history():
    """
    Loads all saved training runs from results/training_history.json.

    Returns:
        list of dict: List of stored training run records (newest first).
    """
    ensure_results_dir_exists()
    if not os.path.exists(HISTORY_FILE):
        return []

    try:
        with open(HISTORY_FILE, "r") as f:
            history = json.load(f)
            return history
    except Exception as e:
        print(f"Error loading training history: {e}")
        return []


def load_saved_results():
    """
    Scans the results/ folder for past JSON benchmark outputs.

    Returns:
        pd.DataFrame: Table of stored model evaluation records.
    """
    ensure_results_dir_exists()
    records = []

    for f_name in os.listdir(RESULTS_DIR):
        if f_name.endswith("_metrics.json"):
            file_path = os.path.join(RESULTS_DIR, f_name)
            try:
                with open(file_path, "r") as f:
                    data = json.load(f)
                    records.append({
                        "Stock": data.get("stock", "N/A"),
                        "Model": data.get("model", "N/A"),
                        "RMSE": data["metrics"].get("RMSE", 0),
                        "MAE": data["metrics"].get("MAE", 0),
                        "MAPE (%)": data["metrics"].get("MAPE", 0),
                        "Timestamp": data.get("timestamp", "")[:19].replace("T", " ")
                    })
            except Exception:
                continue

    if records:
        return pd.DataFrame(records)
    return pd.DataFrame(columns=["Stock", "Model", "RMSE", "MAE", "MAPE (%)", "Timestamp"])
